1.Extract data from the givenSalaryGender CSV file and store the data from each column in a separate NumPy array

In [1]:
import os

In [3]:
os.getcwd()

'C:\\Users\\ssson'

In [4]:
os.chdir('C:\\Users\\ssson\\OneDrive\\Desktop\\JUPYTER WORK NOTEBOOK - NIMISHA')

In [8]:
import pandas as pd
Salarydata = pd.read_csv('SalaryGender.csv')

In [9]:
Salarydata

Salary  Gender  Age  PhD
0   140.00       1   47    1
1    30.00       0   65    1
2    35.10       0   56    0
3    30.00       1   23    0
4    80.00       0   53    1
5    30.00       0   27    0
6    60.00       1   53    0
7    31.10       0   30    0
8   125.00       1   44    1
9    51.00       1   63    1
10    3.00       1   22    0
11   46.00       1   59    0
12  150.00       1   60    1
13    3.00       1   28    0
14  130.00       1   65    0
15   15.00       0   25    0
16  130.00       1   65    0
17   84.00       0   47    1
18  190.00       1   66    1
19   74.00       1   45    1
20   73.00       0   46    0
21   10.00       0   24    0
22   50.00       0   60    0
23    7.00       0   63    0
24    9.50       0   27    0
25   15.20       1   66    1
26   28.60       1   36    1
27   20.00       0   30    0
28   72.00       0   51    1
29   81.00       1   65    1
..     ...     ...  ...  ...
70   40.70       0   57    0
71   15.00       1   23    0
72    0.25       0   53    0
73  152.00       1   71    1
74   39.80       0   20    0
75   12.00       0   27    0
76   30.00       1   69    1
77  120.00       1   58    1
78    1.70       1   37    0
79   36.00       1   32    1
80   96.00       1   33    1
81   38.00       0   32    1
82   90.00       1   60    0
83    9.00       1   71    0
84   25.80       0   30    0
85   22.00       0   62    0
86   38.80       0   54    0
87   72.00       1   42    1
88   89.00       1   62    0
89   41.00       0   51    1
90   89.00       1   71    1
91   25.00       0   29    0
92   52.00       1   55    1
93  115.00       0   54    0
94   66.00       0   55    1
95   18.60       1   26    0
96  152.00       1   56    1
97    1.80       1   28    0
98   35.00       0   44    0
99    4.00       0   24    0

[100 rows x 4 columns]

In [12]:
# storing salarydata column in seperate numpy array.

import numpy as np

salary = np.array(Salarydata['Salary'])
gender = np.array(Salarydata['Gender'])
age = np.array(Salarydata['Age'])
phd = np.array(Salarydata['PhD'])



In [13]:
salary

array([140.  ,  30.  ,  35.1 ,  30.  ,  80.  ,  30.  ,  60.  ,  31.1 ,
       125.  ,  51.  ,   3.  ,  46.  , 150.  ,   3.  , 130.  ,  15.  ,
       130.  ,  84.  , 190.  ,  74.  ,  73.  ,  10.  ,  50.  ,   7.  ,
         9.5 ,  15.2 ,  28.6 ,  20.  ,  72.  ,  81.  , 100.  ,  90.  ,
        90.  ,  35.  ,  30.  ,  25.  ,  52.  ,   9.  ,  63.  ,  72.  ,
        16.  ,  92.  , 106.  ,   2.5 ,   9.  ,  32.  ,  32.  ,  55.  ,
        52.  ,  28.  ,  20.  ,  14.7 ,  22.3 ,  34.8 ,  84.  ,  19.  ,
       160.  ,  65.  ,  55.  ,   4.6 , 102.  ,  20.  ,  62.  ,  55.  ,
        45.6 ,  40.  ,  24.  ,  35.  ,  48.  ,  20.  ,  40.7 ,  15.  ,
         0.25, 152.  ,  39.8 ,  12.  ,  30.  , 120.  ,   1.7 ,  36.  ,
        96.  ,  38.  ,  90.  ,   9.  ,  25.8 ,  22.  ,  38.8 ,  72.  ,
        89.  ,  41.  ,  89.  ,  25.  ,  52.  , 115.  ,  66.  ,  18.6 ,
       152.  ,   1.8 ,  35.  ,   4.  ])


2.Find:  
1. The number of men with a PhD 
2. The number of women with a PhD

In [15]:
Salarydata.columns

Index(['Salary', 'Gender', 'Age', 'PhD'], dtype='object')

In [19]:
men_count = 0
women_count = 0

for i in range(0,100):
    if gender[i] ==1 and phd[i]==1:
        men_count += 1
    if gender[i]==0 and phd[i]==1:
        women_count += 1
print(men_count)
print(women_count)

24
15




3.Use SalaryGender CSV file. Store the “Age” and “PhD” columns in one DataFrame and delete the data of all people who don’t have a PhD

In [22]:
Df = pd.DataFrame()
Df['Age']= age
Df['Phd']= phd

for i in range(0,100):
    if Df.loc[i]['Phd']==0:
        Df = Df.drop(i)
        
print(Df)        
        

    Age  Phd
0    47    1
1    65    1
4    53    1
8    44    1
9    63    1
12   60    1
17   47    1
18   66    1
19   45    1
25   66    1
26   36    1
28   51    1
29   65    1
30   45    1
31   52    1
32   54    1
38   34    1
41   58    1
42   77    1
45   48    1
47   49    1
49   65    1
54   49    1
56   61    1
57   43    1
60   66    1
63   56    1
73   71    1
76   69    1
77   58    1
79   32    1
80   33    1
81   32    1
87   42    1
89   51    1
90   71    1
92   55    1
94   55    1
96   56    1




4.Calculate the total number of people who have a PhD degreefrom SalaryGender CSV file

In [24]:
Phdholder = sum(Df['Phd'])

In [26]:
Phdholder

39



5.How  do  you  Count  The  Number  Of  Times  Each  Value  Appears  In  An  Array  Of Integers?[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]

In [28]:
array = np.array([0,5,4,0,4,4,3,0,0,5,2,1,1,9])

In [32]:
np.bincount(array)

array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1], dtype=int64)



6.Create a numpyarray [[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]]) and filter the elements greater than 5.

In [34]:
arr = np.array([[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]])

In [35]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
arr>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11])

In [44]:
print(f'The items greater than 5 are :')
print(arr[arr>5])

The items greater than 5 are :
[ 6  7  8  9 10 11]




7.Create a numpy array having NaN (Not a Number) and print it.array([ nan,   1.,   2.,  nan,   3.,   4.,   5.])

Print the same array omitting all elements which are nan.

In [62]:
number = np.array([ np.nan, 1, 2, np.nan, 3, 4, 5])

In [63]:
number

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [64]:
number[~np.isnan(number)]

array([1., 2., 3., 4., 5.])

In [65]:
number[np.isnan(number)]

array([nan, nan])




8.Create  a  10x10  array  with  random  values  and  find  the  minimum  and  maximum values.

In [68]:
random = np.random.random((10*10))

In [69]:
random

array([2.57232866e-01, 3.13855367e-02, 1.44675933e-01, 5.48948729e-02,
       2.18418965e-01, 6.40239713e-01, 7.52465425e-01, 2.01792028e-01,
       3.11934762e-01, 5.57705866e-01, 8.28698287e-01, 2.29257552e-01,
       9.41848249e-01, 5.53113784e-01, 5.51784420e-01, 7.75419138e-01,
       4.64569606e-02, 4.95834141e-02, 5.96620547e-01, 4.00753431e-01,
       9.90113361e-01, 9.37756804e-01, 8.26105191e-01, 2.37618359e-01,
       7.01305049e-01, 5.54742294e-01, 3.75010184e-01, 5.68402460e-01,
       7.05226024e-01, 4.05372802e-01, 8.47072194e-01, 3.45188572e-01,
       2.49262377e-01, 3.13922143e-01, 5.54564658e-01, 2.68376801e-01,
       4.62669221e-01, 7.01298434e-01, 1.31437850e-01, 4.62076386e-01,
       9.81858271e-01, 9.18348289e-01, 4.97640009e-01, 6.37769903e-01,
       5.33904306e-02, 6.67596083e-01, 6.68771193e-01, 1.92898999e-01,
       2.74488469e-01, 3.46371336e-01, 3.08906776e-01, 1.13692542e-02,
       4.85258021e-01, 3.17500190e-01, 5.32267977e-01, 8.13760821e-01,
      

In [70]:
max(random)

0.9901133605121502

In [71]:
min(random)

0.00013789875799552487




9.Create a random vector of size 30 and find the mean value.

In [72]:
ran = np.random.random(30)

In [73]:
ran

array([0.51388015, 0.87040222, 0.79280209, 0.17283499, 0.05056352,
       0.57404029, 0.15980626, 0.64793244, 0.56578462, 0.48993744,
       0.60200233, 0.46243362, 0.22645537, 0.35951041, 0.25445973,
       0.43503691, 0.95784992, 0.58454634, 0.91139034, 0.19212009,
       0.14733017, 0.06602875, 0.39386203, 0.55547082, 0.81756482,
       0.75450266, 0.43696712, 0.29809042, 0.03813405, 0.76923019])

In [74]:
ran.mean()

0.47003233618333706




10.Create numpy array having elements 0 to 10 And negate all the elements between 3 and 9

In [76]:
array = np.arange(11)

In [77]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
array[(3< array) & (9> array)]

array([], dtype=int32)

In [82]:
array

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])




11.Create a random array of 3 rows and 3 columns and sort it according to 1stcolumn, 2ndcolumn or 3rdcolumn.

In [83]:
ranno = np.random.randint(0,10,(3,3))

In [84]:
ranno[ranno[:,1].argsort()]

array([[5, 1, 7],
       [6, 3, 0],
       [1, 6, 3]])




12.Create a random array and swap two rows of an array.

In [85]:
A = np.arange(25).reshape(5,5)

In [87]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
A[[0,1]] = A[[1, 0]]

In [94]:
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
