In [1]:
# numpy is an package which helps to create an ARRAY.
# numpy use for mathmetical calculation.
# it will ease the calculation as we do not need to use every time condition .
# array is a one dimensional.
# metrices is two dimensional 

In [2]:
import numpy as np

In [3]:
sales = [2345,5682,1425,4154]

In [4]:
sales_array = np.array(sales)

In [5]:
profit = [425,218,814,317]

In [6]:
profit_array = np.array(profit)

In [7]:
profit_array/sales_array

array([0.18123667, 0.03836677, 0.57122807, 0.07631199])

In [8]:
sales*3

[2345, 5682, 1425, 4154, 2345, 5682, 1425, 4154, 2345, 5682, 1425, 4154]

In [9]:
sales_array*3  # array will do multiplication in individual array not repetiton of number .

array([ 7035, 17046,  4275, 12462])

In [10]:
sales_array

array([2345, 5682, 1425, 4154])

In [11]:
list = [32,33,45,67,89,43]

In [13]:
array = np.array(list) # this way converted list into array.

In [15]:
array

array([32, 33, 45, 67, 89, 43])

In [16]:
array1 = array.copy() # igt will copy entire value

In [17]:
array1

array([32, 33, 45, 67, 89, 43])

In [18]:
array2 = array1[0:4] # created array with slicing of array 2

In [19]:
array2

array([32, 33, 45, 67])

In [20]:
# INDEXING IN ARRAY

array2[2]=56

In [21]:
array2

array([32, 33, 56, 67])

In [22]:
 array1 # can see updation in array2 done updation in array1 because array2 is slicing of array1.

array([32, 33, 56, 67, 89, 43])

In [23]:
array1[0]=100

In [24]:
array1

array([100,  33,  56,  67,  89,  43])

In [25]:
array
# when we do copy from one array to other then updation wont apply in both array table. as array1 changed index 0 - 100
#  wont change value of index 0 - 32 in original table array.

array([32, 33, 45, 67, 89, 43])

In [26]:
# when there is a str in list and rest value are number and we convert list into array all number will convert into string.

list = [1,2,4,6,'A']

In [27]:
list

[1, 2, 4, 6, 'A']

In [28]:
type(list)

list

In [29]:
array_covert_list = np.array(list)

In [30]:
array_covert_list

array(['1', '2', '4', '6', 'A'], dtype='<U11')

In [31]:
type(array_covert_list)

numpy.ndarray