In [1]:
import numpy as np

In [2]:
a = np.array([[1,2], [3,4]])

In [3]:
print(a)

[[1 2]
 [3 4]]


In [4]:
list1 = [1,2,3,4,5]

In [5]:
arr = np.array(list1)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
# Creating numpy Array of specified range


arr = np.arange(10,100)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [8]:
# Creating 5 * 5 arrays of zero

arr_of_zero = np.zeros((5,5))
print(arr_of_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# Creating a linear spaced vector with spacing

vector = np.linspace(0,25,5)
vector

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

In [10]:
# Creating array from existing Data
# numpy.asarray used for converting python sequence into ndarrays.

x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [11]:
type(a)

numpy.ndarray

In [12]:
type(x)

list

In [13]:
# Reshape Numpy array

# converting linear array of 8 element into a 2*2*2 3darray

arr = np.zeros(8)
arr3d = arr.reshape((2,2,2))
print(arr3d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [14]:
# flatten the 3dzeros array # raven function use to flaten the array

arr = np.zeros(8)
arr3d = arr.reshape((2,2,2))
arr = arr3d.ravel()
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
type(arr)

numpy.ndarray

# Indexing and Slicing

In [17]:
arr  = np.arange(2,20)
element = arr[6]
print(element)

8


In [18]:
arr = np.arange(20)
arr_slice = slice(1,10,2)

element= arr[6]

print(arr[arr_slice])

[1 3 5 7 9]


In [19]:
arr_slice

slice(1, 10, 2)

In [20]:
element

6

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
arr[:15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

# NUMPY ARRAY ATTRIBUTES

In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
a.shape

(3, 3)

In [31]:
a.ndim

2

In [33]:
print(a.itemsize)

4


In [34]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
s = np.empty([3,2], dtype = int)
s

array([[1068932208,        364],
       [         0,          0],
       [         1,          0]])

# Pandas - series type

In [45]:
# A series is a single-dimensional array structures that stores homogenous data

In [46]:
import pandas as pd

In [47]:
series = pd.Series()
series

Series([], dtype: float64)

In [48]:
#creating series from an Ndarray

In [49]:
arr = np.array([10,20,30,40,50])
series = pd.Series(arr)
series

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [50]:
# creating series from python dictionary

In [51]:
data = {'a':10, 'b':20 , 'c': 30}
series = pd.Series(data)
series

a    10
b    20
c    30
dtype: int64

In [52]:
# slicing

In [53]:
series[2]

30

In [54]:
a = pd.Series([11,12,14,16,23])

In [55]:
a[:-1]

0    11
1    12
2    14
3    16
dtype: int64

In [56]:
a[0:3]

0    11
1    12
2    14
dtype: int64

In [57]:
a[: :]

0    11
1    12
2    14
3    16
4    23
dtype: int64

In [58]:
a[: : -1]

4    23
3    16
2    14
1    12
0    11
dtype: int64

# PANDAS DATAFRAME

In [59]:
a = [10,20,50,80,100]
df = pd.DataFrame(a)

In [60]:
df

0
0   10
1   20
2   50
3   80
4  100

In [61]:
# creating a data frame from a list of dictionaries

v = [{'a' : 1 , 'b' :3}, {'a' : 5 ,'b' :6 , 'c':10}]
v

[{'a': 1, 'b': 3}, {'a': 5, 'b': 6, 'c': 10}]

In [62]:
df1 = pd.DataFrame(v)

In [63]:
df1

a  b     c
0  1  3   NaN
1  5  6  10.0

In [68]:
df1 = pd.DataFrame(v, index = ['First', 'Second']) #index function change index value as per your choice.

In [69]:
df1

a  b     c
First   1  3   NaN
Second  5  6  10.0

In [70]:
# converting a dictionary of series into daatframe

In [71]:
data = {'one': pd.Series([1,2,3], index = ['a', 'b','c']),
       'two' : pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}

In [72]:
data

{'one': a    1
 b    2
 c    3
 dtype: int64, 'two': a    1
 b    2
 c    3
 d    4
 dtype: int64}

In [73]:
data = pd.DataFrame(data)

In [74]:
data

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [75]:
# updation in dataframe

In [78]:
data['three']= pd.Series([10,20,30], index = ['a','b','c'])

In [79]:
data

one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [80]:
# column Deletion using Del function

In [81]:
del data['one']

In [82]:
data

two  three
a    1   10.0
b    2   20.0
c    3   30.0
d    4    NaN

In [83]:
data.pop('two')

a    1
b    2
c    3
d    4
Name: two, dtype: int64

In [84]:
data

three
a   10.0
b   20.0
c   30.0
d    NaN

In [89]:
# data frame row can be select by passing the row lavel to the loc() function

data.loc['c']

three    30.0
Name: c, dtype: float64

In [86]:
data

three
a   10.0
b   20.0
c   30.0
d    NaN

In [90]:
# Row selection can also be done through row index

In [91]:
data.iloc[2]

three    30.0
Name: c, dtype: float64